management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: match-api

redis:
  stream:
    orderbook:
      key-prefix: "orderbook:stream:"
      consumer-group-name: "matching-engine"
      block-timeout: 5s
      batch-size: 10

api:
  trade.base-url: http://trade-api

# KIS API 설정 (실전투자)
kis:
  websocket:
    url: ws://ops.koreainvestment.com:21000
    app-key: key
    app-secret: secret
  auth:
    base-url: https://openapi.koreainvestment.com:9443